adding a console command parser
cs410agile-group3/FTPClient pull request #53
Opened 2019-07-15 01:16 UTC by karikittie

Adding the framework for the console command parser.

2019-07-15 03:22 UTC, mkduer requested changes

2019-07-15 03:22 UTC, mkduer commented on FtpClient/FtpCli/ConsoleParser/ConsoleParser.cs
> +          if (args.Length < 2)
Could there be valid situations where `args.Length == 1`? For example, if we have a command like `ls` it probably wouldn't take additional arguments. Other than that, looks good!

2019-07-15 03:22 UTC, mkduer commented on FtpClient/FtpCli/ConsoleParser/ConsoleParserCommand.cs
> +            this.manyArgsAction = action;
Should `this.manyArgsAction` be initialized and copied into? Example:

`this.manyArgsAction = new List<string>();`
`action.CopyTo(this.manyArgsAction);`

2019-07-15 03:36 UTC, mkduer submitted a review, later dismissed

2019-07-17 01:38 UTC, bnert approved these changes

2019-07-17 01:38 UTC, brent-soles commented
@karikittie, looks good!

2019-07-17 01:42 UTC, bahamieh approved these changes
Cool!

2019-07-17 01:43 UTC, merged